apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ${namespace}
  labels:
    service: backend
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: backend
  selector:
    service: backend