# This is a basic workflow to help you get started with Actions

name: Buildah Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]
    
    env:
        IMAGE_NAME: netcoreapp
        TAGS: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Setup S2i and Build container image
      #- name: Setup and Build
      #  id: build_image
      #  uses: redhat-actions/s2i-build@v2
      #  with:
      #    path_context: '/home/runner/work/netcoretest/netcoretest/Akbank.Sample/Akbank.Sample'
          # Builder image for a .net 5 project
      #    builder_image: 'registry.access.redhat.com/ubi8/dotnet-50'
      #    image: ${{ env.IMAGE_NAME }}
      #    tags: ${{ env.TAGS }}
             
      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: netcoretest
          tags: v1 ${{ github.sha }}
          dockerfiles: |
            /Akbank.Sample/Akbank.Sample/Dockerfile
          extra-args: |
            --storage-opt overlay.ignore_chown_errors=true
            --isolation=chroot
