name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.github_token}}  
    - name: Path lister action
      uses: Rishabh510/Path-lister-action@1.0
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag a1tan/netcoretest:${{ steps.buildnumber.outputs.build_number }} -f  /home/runner/work/netcoretest/Akbank.Sample/Dockerfile
