name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.github_token}}  
    - uses: actions/checkout@v2
    # - name: Microsoft Azure Container Registry Login
    #   # You may pin to the exact commit or the version.
    #   # uses: elgohr/acr-login-action@b088ef4d7c3847f3c14159b968860890482003fa
    #   uses: elgohr/acr-login-action@0.1
    #   with:
    #     # The ACR service principal to use for login
    #     service_principal: ${{secrets.SERVICE_PRINCIPAL}}
    #     # The password of the service principal
    #     service_principal_password: ${{secrets.SERVICE_PRINCIPAL_PASSWORD}}
    #     # The ACR tenant to use for login
    #     tenant: ${{secrets.TENANT}}
    #     # The ACR registry to use
    #     registry: ${{secrets.REGISTRY}}
    #     # The ACR repository to use
    #     repository: ${{secrets.REPOSITORY}}
    - name: Build the Docker image
      working-directory: /home/runner/work/netcoretest/netcoretest/Akbank.Sample
      run: docker build . --tag a1tan/netcoretest:${{ steps.buildnumber.outputs.build_number }} -f  Akbank.Sample/Dockerfile
      
    - name: Login to Docker
      working-directory: /home/runner/work/netcoretest/netcoretest/Akbank.Sample
      run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}} docker.io
      
    - name: Push the Docker image
      working-directory: /home/runner/work/netcoretest/netcoretest/Akbank.Sample
      run: docker push a1tan/netcoretest:${{ steps.buildnumber.outputs.build_number }}
      
    - name: Upload terraform files
      uses: actions/upload-artifact@v2.2.3
      with:
        name: terraform
        path: /home/runner/work/netcoretest/netcoretest/IaC/Terraform/
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.9
      with:
        # Artifact name
        name: terraform
        # Destination path
        path: /terraform
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
    
    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{secrets.AKS_CONTEXT}} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
        context: Arc-AKS-Demo  #If left unspecified, current-context from kubeconfig is used as default
      id: setcontext
    
    - name: Terraform Init
      working-directory: /terraform/provision/app.test-backend/dev.azure
      id: init
      run: terraform init

    - name: Terraform Validate
      working-directory: /terraform/provision/app.test-backend/dev.azure
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      working-directory: /terraform/provision/app.test-backend/dev.azure
      id: plan
      run: terraform plan -no-color -var 'imagetag=${{ steps.buildnumber.outputs.build_number }}' -var 'k8s_config_context=Arc-AKS-Demo' -out=tfplan -input=false
    
    - name: Terraform Apply
      working-directory: /terraform/provision/app.test-backend/dev.azure
      id: apply
      run: terraform apply -input=false tfplan
