# This is a basic workflow to help you get started with Actions

name: Openshift

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      env:
        # These can be stored in secrets, if desired.
        OPENSHIFT_USER: my-username
        OPENSHIFT_NAMESPACE: my-namespace

      with:
        # URL to your OpenShift cluster.
        # Refer to Step 2.
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}

        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        
        insecure_skip_tls_verify: true
